services:
  prepare-dataset:
    build:
      context: .
      dockerfile: Dockerfile
    image: cow-classifier:py312-slim
    container_name: prepare-dataset
    environment:
      PYTHONUNBUFFERED: "1"
      PASTA_ORIGINAL: /app/fotos_anotadas
      BASE_DIR: /app/dataset
      K: "5"
      MODEL_DIR: /app/models
      DETECTION_MODEL_NAME: yolo11x.pt
      POSE_MODEL_NAME: yolo11x-pose.pt
      YOLO_CONFIG_DIR: /app/.ultralytics
    volumes:
      - ./fotos_anotadas:/app/fotos_anotadas
      - ./dataset:/app/dataset
      - ./dataset_samples:/app/dataset_samples
      - ./models:/app/models:ro
      - ./.ultralytics:/app/.ultralytics
      - ./src:/app/src
    command: ["python", "src/key_point_detection_cow.py"]
